---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
---

<!-- Reproducible Research: Peer Assessment 1 -->
<!-- ======================================== -->

```{r setoptions}
knitr::opts_chunk$set(echo = TRUE)

```


## Loading and preprocessing the data
```{r}
library(data.table)

activity <- fread(unzip("activity.zip"))
activity$date <- as.Date(activity$date)
summary(activity)
```



## What is mean total number of steps taken per day?
```{r}
library(magrittr)
activityDay <- activity[,.(stepsDay=sum(steps, na.rm=T)),by=date] 
meanDay <- activityDay[,mean(stepsDay,na.rm = T)]
medianDay <- activityDay[,median(stepsDay,na.rm = T)]
hist(activityDay$stepsDay,xlab = "Steps per Day", main = "Histogram of the number of steps per day")
```

The mean number of steps per day is `r meanDay` and the median `r medianDay`


## What is the average daily activity pattern?



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
